### ISSUE TITLE
Cached local db isn't updated when new file is saved to file system

### ISSUE THREAD

**Issue by jpvantuyl** [perfectapi/ChromeKeePass#15]
When I save an updated .kdbx to my chosen Chrome Local Storage directory (e.g. C:\keepass\myfile.kdbx) the changes are not automatically picked up by the extension.

Perhaps it's a documentation issue?  Not sure if Chrome local storage even supports that kind of relationship with the native OS's folders.

My workaround was to delete the file from local storage and load it again from the same directory.

**Comment by DukeyToo** [comment]
Yeah, I think this is more of a documentation or usability issue.  The "local storage" is a copy with no link to the original folder.   

It is not necessary to delete it in order to update it though - you can just upload it again and it will overwrite the old copy.

I'll leave this bug open so that I can make it more intuitive.

**Comment by DukeyToo** [comment]
Updated the text so it is a lot clearer now
